In [103]:
import numpy as np
import torch
import torchmetrics

import matplotlib.pyplot as plt

In [104]:
target1 = np.array([[0], [1], [0], [1], [0], [0]])
pred1 = np.array([[0.7], [0.4], [0.3], [0.8], [0.6], [0.2]])
target2 = np.array([[0], [1], [0], [1], [0], [0]])
pred2 = np.array([[0.7], [0.3], [0], [0.6], [0], [0.3]])

In [105]:
tg1 = torch.tensor(target1)
pd1 = torch.tensor(pred1)
tg2 = torch.tensor(target2)
pd2 = torch.tensor(pred2)

l_tg = [tg1, tg2]
l_pd = [pd1, pd2]

In [106]:
# initialize metric
metric_acc = torchmetrics.classification.BinaryAccuracy()
metric_pre = torchmetrics.classification.BinaryPrecision()
metric_rec = torchmetrics.classification.BinaryRecall()
metric_f1 = torchmetrics.classification.BinaryF1Score()

n_batches = 2
for i in range(n_batches):
    # simulate a classification problem
    acc = metric_acc(l_pd[i], l_tg[i])
    pre = metric_pre(l_pd[i], l_tg[i])
    rec = metric_rec(l_pd[i], l_tg[i])
    f1 = metric_f1(l_pd[i], l_tg[i])
    print(f"Accuracy on batch {i}: {acc}")
    print(f"Precision on batch {i}: {pre}")
    print(f"Recall on batch {i}: {rec}")
    print(f"F1 on batch {i}: {f1}")

# metric on all batches using custom accumulation
acc = metric_acc.compute()
pre = metric_pre.compute()
rec = metric_rec.compute()
f1 = metric_f1.compute()
print(f"Accuracy on all data: {acc}")
print(f"Precision on all data: {pre}")
print(f"Recall on all data: {rec}")
print(f"F1 on all data: {f1}")

# Resetting internal state such that metric ready for new data
metric_acc.reset()
metric_pre.reset()
metric_rec.reset()
metric_f1.reset()

Accuracy on batch 0: 0.5
Precision on batch 0: 0.3333333432674408
Recall on batch 0: 0.5
F1 on batch 0: 0.4000000059604645
Accuracy on batch 1: 0.6666666865348816
Precision on batch 1: 0.5
Recall on batch 1: 0.5
F1 on batch 1: 0.5
Accuracy on all data: 0.5833333134651184
Precision on all data: 0.4000000059604645
Recall on all data: 0.5
F1 on all data: 0.4444444477558136


# Multilabel

In [107]:
y1 = torch.tensor(np.array([[0, 1], [1, 0]]))     
yhat1 = torch.sigmoid(torch.tensor(np.array([[-2, 1], [2, 3]])))
    
y2 = torch.tensor(np.array([[1, 1], [0, 0]]))     
yhat2 = torch.sigmoid(torch.tensor(np.array([[2, 1], [-2, -0.5]])))

batches_y = [y1, y2]
batches_yhat = [yhat1, yhat2]
print(f'Target: {batches_y}')
print(f'Preds: {batches_yhat}')

Target: [tensor([[0, 1],
        [1, 0]]), tensor([[1, 1],
        [0, 0]])]
Preds: [tensor([[0.1192, 0.7311],
        [0.8808, 0.9526]]), tensor([[0.8808, 0.7311],
        [0.1192, 0.3775]], dtype=torch.float64)]


In [108]:
conf_metric = torchmetrics.classification.MultilabelConfusionMatrix(num_labels = 2, threshold = 0.5)

n_batches = 2
for i in range(n_batches):
    # simulate a classification problem
    conf_mtx = conf_metric(batches_yhat[i], batches_y[i])

conf_mtx = conf_metric.compute()
print(conf_mtx)

tensor([[[2, 0],
         [0, 2]],

        [[1, 1],
         [0, 2]]])


In [109]:
precision_metric = torchmetrics.classification.MultilabelPrecision(num_labels = 2, threshold = 0.5, average = None)
recall_metric = torchmetrics.classification.MultilabelRecall(num_labels = 2, threshold = 0.5, average = None)
accuracy_metric = torchmetrics.classification.MultilabelAccuracy(num_labels = 2, threshold = 0.5, average = None)
f1_metric = torchmetrics.classification.MultilabelF1Score(num_labels = 2, threshold = 0.5, average = None)


n_batches = 2
for i in range(n_batches):
    # simulate a classification problem
    precision = precision_metric(batches_yhat[i], batches_y[i])
    recall = recall_metric(batches_yhat[i], batches_y[i])
    accuracy = accuracy_metric(batches_yhat[i], batches_y[i])
    f1 = f1_metric(batches_yhat[i], batches_y[i])

precision = precision_metric.compute()
recall = recall_metric.compute()
accuracy = accuracy_metric.compute()
f1 = f1_metric.compute()

print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'Accuracy: {accuracy}')
print(f'F1: {f1}')

Precision: tensor([1.0000, 0.6667])
Recall: tensor([1., 1.])
Accuracy: tensor([1.0000, 0.7500])
F1: tensor([1.0000, 0.8000])


# My Precision Metric

In [110]:
# target1 = np.array([[0], [1], [0], [1], [0], [0]])
# pred1 = np.array([[0.7], [0.6], [0.3], [0.8], [0.6], [0.2]])
# target2 = np.array([[0], [1], [0], [1], [0], [0]])
# pred2 = np.array([[1], [1], [0], [1], [0], [0]])

In [111]:
# tg1 = torch.tensor(target1, dtype=torch.float32)
# pd1 = torch.tensor(pred1, dtype=torch.float32)
# tg2 = torch.tensor(target2, dtype=torch.float32)
# pd2 = torch.tensor(pred2, dtype=torch.float32)

# l_tg = [tg1, tg2]
# l_pd = [pd1, pd2]

In [112]:
l_pd

[tensor([[0.7000],
         [0.4000],
         [0.3000],
         [0.8000],
         [0.6000],
         [0.2000]], dtype=torch.float64),
 tensor([[0.7000],
         [0.3000],
         [0.0000],
         [0.6000],
         [0.0000],
         [0.3000]], dtype=torch.float64)]

In [113]:
# initialize metric
metric_acc = torchmetrics.classification.BinaryAccuracy()
metric_pre = torchmetrics.classification.BinaryPrecision()
metric_rec = torchmetrics.classification.BinaryRecall()
metric_f1 = torchmetrics.classification.BinaryF1Score()

n_batches = 2
for i in range(n_batches):
    # simulate a classification problem
    acc = metric_acc(l_pd[i], l_tg[i])
    pre = metric_pre(l_pd[i], l_tg[i])
    rec = metric_rec(l_pd[i], l_tg[i])
    f1 = metric_f1(l_pd[i], l_tg[i])
    print(f"Accuracy on batch {i}: {acc:.3f}")
    print(f"Precision on batch {i}: {pre:.3f}")
    print(f"Recall on batch {i}: {rec:.3f}")
    print(f"F1 on batch {i}: {f1:.3f}")

# metric on all batches using custom accumulation
acc = metric_acc.compute()
pre = metric_pre.compute()
rec = metric_rec.compute()
f1 = metric_f1.compute()
print(f"Accuracy on all data: {acc:.3f}")
print(f"Precision on all data: {pre:.3f}")
print(f"Recall on all data: {rec:.3f}")
print(f"F1 on all data: {f1:.3f}")

# Resetting internal state such that metric ready for new data
metric_acc.reset()
metric_pre.reset()
metric_rec.reset()
metric_f1.reset()

Accuracy on batch 0: 0.500
Precision on batch 0: 0.333
Recall on batch 0: 0.500
F1 on batch 0: 0.400
Accuracy on batch 1: 0.667
Precision on batch 1: 0.500
Recall on batch 1: 0.500
F1 on batch 1: 0.500
Accuracy on all data: 0.583
Precision on all data: 0.400
Recall on all data: 0.500
F1 on all data: 0.444


In [114]:
l_pd_round = [torch.round(pd) for pd in l_pd]
l_pd_round

[tensor([[1.],
         [0.],
         [0.],
         [1.],
         [1.],
         [0.]], dtype=torch.float64),
 tensor([[1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.]], dtype=torch.float64)]

In [115]:
print(l_pd_round[0])
print(l_tg[0])

tensor([[1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.]], dtype=torch.float64)
tensor([[0],
        [1],
        [0],
        [1],
        [0],
        [0]])


# Accuracy

In [116]:
eq_tensor = torch.eq(l_pd_round[0], l_tg[0])
print(eq_tensor)

tensor([[False],
        [False],
        [ True],
        [ True],
        [False],
        [ True]])


In [117]:
torch.count_nonzero(eq_tensor)

tensor(3)

In [118]:
my_acc = torch.count_nonzero(eq_tensor) / eq_tensor.size()[0]

In [119]:
my_acc

tensor(0.5000)

# Precision

In [120]:
pred_true = l_pd_round[0] == 1
pred_true

tensor([[ True],
        [False],
        [False],
        [ True],
        [ True],
        [False]])

In [121]:
target_true = l_tg[0] == 1
target_true

tensor([[False],
        [ True],
        [False],
        [ True],
        [False],
        [False]])

In [122]:
n_true = torch.count_nonzero(target_true)
n_true

tensor(2)

In [123]:
torch.eq(pred_true, target_true)*target_true

tensor([[False],
        [False],
        [False],
        [ True],
        [False],
        [False]])

In [124]:
my_prec = torch.count_nonzero(torch.eq(pred_true, target_true)*target_true) / torch.count_nonzero(pred_true)

In [125]:
my_prec

tensor(0.3333)

# Recall

- 1 Multiplicas target * pred = mask_pred
- 2 Recall = non_zero(mask_pred) / non_zero(target)

In [126]:
mask_pred = l_tg[0] * torch.round(l_pd[0])
mask_pred

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.]], dtype=torch.float64)

In [127]:
my_recall = torch.count_nonzero(mask_pred) / torch.count_nonzero(l_tg[0])

In [128]:
my_recall

tensor(0.5000)